//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedData
{
    using System;
    using System.Collections.Generic;
    
    public partial class BroadcastFeed
    {
        public int Id { get; set; }
        public string Message { get; set; }
        public string IPAddress { get; set; }
        public System.DateTime DateAdded { get; set; }
    }
}
