//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public System.Guid Id { get; set; }
        public System.Guid SummaryId { get; set; }
        public bool IsHomeTeam { get; set; }
        public string PlayerName { get; set; }
        public int APIPlayerId { get; set; }
        public byte Minute { get; set; }
        public string Discriminator { get; set; }
        public Nullable<System.Guid> Summary_Id { get; set; }
        public Nullable<System.Guid> Summary_Id1 { get; set; }
        public Nullable<System.Guid> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.Guid> UpdatedByUserId { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    
        public virtual Summary Summary { get; set; }
        public virtual Summary Summary1 { get; set; }
    }
}
