//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public System.Guid Id { get; set; }
        public string Text { get; set; }
        public byte MatchRating { get; set; }
        public byte PlayerRating { get; set; }
        public byte CommentType { get; set; }
        public byte EventType { get; set; }
        public byte Perspective { get; set; }
        public byte Position { get; set; }
        public byte TeamRating { get; set; }
    }
}
