//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HonestAppsEntities : DbContext
    {
        public HonestAppsEntities()
            : base("name=HonestAppsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BroadcastFeed> BroadcastFeeds { get; set; }
        public virtual DbSet<Card> Cards { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Goal> Goals { get; set; }
        public virtual DbSet<Lineup> Lineups { get; set; }
        public virtual DbSet<Match> Matches { get; set; }
        public virtual DbSet<MatchesToday> MatchesTodays { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<PlayerStat> PlayerStats { get; set; }
        public virtual DbSet<Rival> Rivals { get; set; }
        public virtual DbSet<SiteException> SiteExceptions { get; set; }
        public virtual DbSet<Stat> Stats { get; set; }
        public virtual DbSet<Substitution> Substitutions { get; set; }
        public virtual DbSet<Summary> Summaries { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<UpdateHistory> UpdateHistories { get; set; }
    }
}
