//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedData
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeagueStanding
    {
        public System.Guid Id { get; set; }
        public int APIId { get; set; }
        public string Name { get; set; }
        public byte Position { get; set; }
        public byte GamesPlayed { get; set; }
        public byte GamesWon { get; set; }
        public byte GamesDrawn { get; set; }
        public byte GamesLost { get; set; }
        public byte GoalsScored { get; set; }
        public byte GoalsConceded { get; set; }
        public int GoalDifference { get; set; }
        public byte Points { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.Guid> UpdatedByUserId { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    }
}
