//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerStat
    {
        public System.Guid Id { get; set; }
        public System.Guid PlayerId { get; set; }
        public System.Guid MatchId { get; set; }
        public byte PositionX { get; set; }
        public byte PositionY { get; set; }
        public Nullable<byte> TotalShots { get; set; }
        public Nullable<byte> ShotsOnGoal { get; set; }
        public Nullable<byte> Goals { get; set; }
        public Nullable<byte> Assists { get; set; }
        public Nullable<byte> Offsides { get; set; }
        public Nullable<byte> FoulsDrawn { get; set; }
        public Nullable<byte> FoulsCommitted { get; set; }
        public Nullable<byte> Saves { get; set; }
        public Nullable<byte> YellowCards { get; set; }
        public Nullable<byte> RedCards { get; set; }
        public Nullable<byte> PenaltiesScored { get; set; }
        public Nullable<byte> PenaltiesMissed { get; set; }
        public int APIId { get; set; }
        public Nullable<System.Guid> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.Guid> UpdatedByUserId { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public byte Rating { get; set; }
    
        public virtual Match Match { get; set; }
        public virtual Player Player { get; set; }
    }
}
