//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stat
    {
        public System.Guid Id { get; set; }
        public System.Guid MatchId { get; set; }
        public Nullable<byte> HomeTeamTotalShots { get; set; }
        public Nullable<byte> HomeTeamOnGoalShots { get; set; }
        public Nullable<byte> HomeTeamFouls { get; set; }
        public Nullable<byte> HomeTeamCorners { get; set; }
        public Nullable<byte> HomeTeamOffsides { get; set; }
        public string HomeTeamPossessionTime { get; set; }
        public Nullable<byte> HomeTeamYellowCards { get; set; }
        public Nullable<byte> HomeTeamRedCards { get; set; }
        public Nullable<byte> HomeTeamSaves { get; set; }
        public Nullable<byte> AwayTeamTotalShots { get; set; }
        public Nullable<byte> AwayTeamOnGoalShots { get; set; }
        public Nullable<byte> AwayTeamFouls { get; set; }
        public Nullable<byte> AwayTeamCorners { get; set; }
        public Nullable<byte> AwayTeamOffsides { get; set; }
        public string AwayTeamPossessionTime { get; set; }
        public Nullable<byte> AwayTeamYellowCards { get; set; }
        public Nullable<byte> AwayTeamRedCards { get; set; }
        public Nullable<byte> AwayTeamSaves { get; set; }
        public Nullable<System.Guid> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.Guid> UpdatedByUserId { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public byte HomeTeamRating { get; set; }
        public byte AwayTeamRating { get; set; }
        public byte MatchRating { get; set; }
    
        public virtual Match Match { get; set; }
    }
}
