// <auto-generated />
namespace CMS.EntitiesMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddLeagueStandings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddLeagueStandings));
        
        string IMigrationMetadata.Id
        {
            get { return "201612091851514_AddLeagueStandings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
