// <auto-generated />
namespace CMS.EntitiesMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class LineupAddPosition2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LineupAddPosition2));
        
        string IMigrationMetadata.Id
        {
            get { return "201610021635142_LineupAddPosition2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
